# fly.toml app configuration file generated for doc-quiet-frog-9195 on 2025-10-31T11:41:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "unsudo-doc"
primary_region = "ams"

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1